const earbud = [
  {
    id: 1,
    title:
      "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, IPX4 Water Resistance, ENx Tech, IWP, Smooth Touch Controls(Cyan Cider)",
    img: "https://m.media-amazon.com/images/I/31BMd11KciL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/51IIMMnQ7cL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/81NXl8ObnEL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Dbhs4BLZL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/71DxKhGrLuL._SY450_.jpg",
    price: 4490,
    discount: 78,
    qty: 1,
    category: "earbud",
  },
  {
    id: 2,
    title:
      "CrossBeats Newly launched Revolt Hybrid Active Noise Cancelling Wireless Bluetooth Earbuds, 48hrs Playtime TWS, 10 mm Ti-Alloy Driver, EchoBlast™, 40ms Low Latency Earphone-Black",
    img: "https://m.media-amazon.com/images/I/61J9BzebDnL._SY450_.jpg",
    img2: "https://m.media-amazon.com/images/I/61f1IQifWXL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/61axYGTUdVL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/81o04TvhnIL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/61t9SMyZ9aL._SY450_.jpg",
    price: 9999,
    discount: 75,
    qty: 1,
    category: "earbud",
  },
  {
    id: 3,
    title:
      "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design + AI Noise Cancellation, IP55 Rating, Fast Charging (Black Slate)",
    img: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/51gX3E0vzjL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/41-vUVwh5VL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/51PDeyFzo1L._SL1500_.jpg",
    price: 2999,
    discount: 7,
    qty: 1,
    category: "earbud",
  },
  {
    id: 4,
    title:
      "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with Mic, Type-C Fast Charging, IPX4 & Voice Assistance (Black)",
    img: "https://m.media-amazon.com/images/I/31G1NouVxaL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/61Coiv6SLXL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/61jkqxMB4jL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/51+tZ3xiA7L._SL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/51wi0sZVqyL._SL1100_.jpg",
    price: 2599,
    discount: 71,
    qty: 1,
    category: "earbud",
  },
  {
    id: 5,
    title:
      "Boult Audio Z25 True Wireless in Ear Earbuds with 32H Playtime, 45ms Low Latency, Type-C Fast Charging (10=150Mins), Made in India, Zen ENC Mic, 13mm Bass Drivers, Bluetooth 5.3 Ear Buds (Blue Moss)",
    img: "https://m.media-amazon.com/images/I/71vlByXS-JL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81KqErUpBOL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/81v+dv-6KAL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71akRKumeCL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/81T79XX+wUL._SL1500_.jpg",
    price: 2999,
    discount: 63,
    qty: 1,
    category: "earbud",
  },
  {
    id: 6,
    title:
      "Boult Audio X30 True Wireless in Ear Earbuds with 40H Playtime, Quad Mic ENC, 45ms Xtreme Low Latency, Made in India, Type-C Fast Charging, 3 Equalizer Modes (Rock, BoomX, Hi-Fi), BT 5.1 (Blue)",
    img: "https://m.media-amazon.com/images/I/71ey9w1JYTL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71xO47tyYsL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71m50Eny0EL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61RgoMA9XDL._SL1500_.jpg",
    img5: "	https://m.media-amazon.com/images/I/81OBQ+eI1uL._SL1500_.jpg",
    price: 4999,
    discount: 70,
    qty: 1,
    category: "earbud",
  },
  {
    id: 7,
    title:
      "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
    img: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61j3VLyxkHL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61aBVyNtImL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71JFUxjducL._SL1500_.jpg",
    price: 2990,
    discount: 57,
    qty: 1,
    category: "earbud",
  },
  {
    id: 8,
    title:
      "Blaupunkt BTW07 ANC Moksha-30Db Bluetooth Truly Wireless In Ear Earbuds with Mic, Flip Top Rotatory Design, 40H Playtime, TurboVolt Fast Charging, Crispr Enc Tech, GameOn with 80Ms Low Latency (Black)",
    img: "https://m.media-amazon.com/images/I/31XeLoY52sL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/61iJdWkaQ+L._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71Tg5d5phGL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/61KdB+bNUFL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/61lxhBySpLL._SY450_.jpg",
    price: 5999,
    discount: 58,
    qty: 1,
    category: "earbud",
  },
  {
    id: 10,
    title: `pTron Bassbuds Fute 5.1 Bluetooth Truly Wireless Featherlite TWS in Ear Earbuds with Mic 25Hrs Playtime, 13Mm Dynamic Driver, Immersive Audio, Touch Control, Voice Assistance & Fast Charging (Black)`,
    img: "https://m.media-amazon.com/images/I/51PNGyUNvmL._SL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61dElFbRplL._SL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/51Im+twUG4L._SL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61un6wGaIjL._SL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/513-c5luOmL._SL1100_.jpg",
    price: 3299,
    discount: 79,
    qty: 1,
    category: "earbud",
  },
  {
    id: 11,
    title: `Boult Audio X1 Buds True Wireless in Ear Earbuds with 24H Playtime, Quad Mic ENC, Made in India, Type-C Fast Charging, Environmental Noise Cancellation, 10mm Bass Drivers, TWS Airbass ear buds (Black)`,
    img: "https://m.media-amazon.com/images/I/71mT2gCHH+L._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81Nov7kscML._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/91teZ0CgAKL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71aL6iUS8KL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71o4W7JuPtL._SL1500_.jpg",
    price: 6999,
    discount: 74,
    qty: 1,
    category: "earbud",
  },
  {
    id: 12,
    title: `Boult Audio Powerbuds True Wireless in Ear Earbuds with 120H Playtime, in-Built Powerbank, Type-C Fast Charging, Made in India, Pro+ Calling HD Mic, IPX7 Waterproof, Bluetooth Ear Buds TWS (Black)`,
    img: "https://m.media-amazon.com/images/I/71jrExswt4L._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71HAe9bru5L._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71wUXtQVVjL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/81r6fKyraKL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71-cfdI-CBL._SL1500_.jpg",
    price: 8999,
    discount: 83,
    qty: 1,
    category: "earbud",
  },
  {
    id: 13,
    title: `Noise Buds Vs104 Bluetooth Truly Wireless in Ear Earbuds with Mic, 30-Hours of Playtime, Instacharge, 13Mm Driver and Hyper Sync (Charcoal Black)`,
    img: "https://m.media-amazon.com/images/I/51cjIEYU8BL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61gE89QmD+L._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/51r57IhfBwL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/513az8Cho7L._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/517pNu7bWJL._SL1500_.jpg",
    price: 3499,
    discount: 69,
    qty: 1,
    category: "earbud",
  },
];
const tshirt = [
  {
    id: 101,
    title: `Allen Solly Men's Regular Fit Polo`,
    img: "https://m.media-amazon.com/images/I/71eUwDk8z+L._UY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/71mh8ZJZFuL._UX569_.jpg",
    img3: "https://m.media-amazon.com/images/I/71vSLpVgZpL._UX569_.jpg",
    img4: "https://m.media-amazon.com/images/I/71J8pbcn8WL._UX569_.jpg",
    img5: "https://m.media-amazon.com/images/I/71Xu6C8X5sL._UX569_.jpg",
    price: 1099,
    discount: 47,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 102,
    title: `Veirdo Polo T Shirts for Men, Cotton Polo Neck T Shirts for Men, Half Sleeves Men Polo Tshirt, Classic Polo T Shirts for Men, Men's Regular Polo Shirt`,
    img: "https://m.media-amazon.com/images/I/51lP3VinwoL._UY879_.jpg",
    img2: "https://m.media-amazon.com/images/I/313gxA5aDLL._SR38,50_.jpg",
    img3: "https://m.media-amazon.com/images/I/51p4Lh0xBBL._UX569_.jpg",
    img4: "https://m.media-amazon.com/images/I/61b610JzsZL._UX569_.jpg",
    img5: "https://m.media-amazon.com/images/I/512nCuSkPvL._UX679_.jpg",
    price: 1199,
    discount: 68,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 103,
    title: `AUSK Men's Henley Neck Full Sleeves Regular Fit Cotton T-Shirts`,
    img: "https://m.media-amazon.com/images/I/7152RCSU4LL._UX569_.jpg",
    img2: "https://m.media-amazon.com/images/I/61sN03JSBVL._UX569_.jpg",
    img3: "https://m.media-amazon.com/images/I/61sJSqUbdIL._UX569_.jpg",
    img4: "https://m.media-amazon.com/images/I/61orVltZ7aL._UX569_.jpg",
    img5: "https://m.media-amazon.com/images/I/512nCuSkPvL._UX679_.jpg",
    price: 1449,
    discount: 76,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 104,
    title: `Lyned Mens Cotton Half Sleeve Striped Polo T Shirt with Collar`,
    img: "https://m.media-amazon.com/images/I/71pNnnaOIzS._UY741_.jpg",
    img2: "https://m.media-amazon.com/images/I/81qde+GbXzS._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71OQQEULimS._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61OCQ1emmYS._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/512nCuSkPvL._UX679_.jpg",
    price: 2499,
    discount: 73,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 105,
    title: `AELOMART Men's T Shirt-(Amt250105-P_Green)`,
    img: "https://m.media-amazon.com/images/I/71O1QaI-sbL._UY741_.jpg",
    img2: "https://m.media-amazon.com/images/I/313hld9yJYL._SR38,50_.jpg",
    img3: "https://m.media-amazon.com/images/I/71IS7Oxhv4L._UY550_.jpg",
    img4: "https://m.media-amazon.com/images/I/71qJJoWrioL._UY550_.jpg",
    img5: "https://m.media-amazon.com/images/I/41TKkmIEiyL.jpg",
    price: 1499,
    discount: 67,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 106,
    title: `Campus Sutra Men's Blue and White Ombre Dri-Fit Activewear T-Shirt Regular Fit for Casual Wear | Structured T-Shirt Crafted with Comfort Fit and High-Performance for Everyday Wear`,
    img: "https://m.media-amazon.com/images/I/61MjKYTzgQS._UX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/41O5F1Fwa-S._SR38,50_.jpg",
    img3: "https://m.media-amazon.com/images/I/71ULOze-C9S._UX679_.jpg",
    img4: "https://m.media-amazon.com/images/I/71VawsSnKaL._UX679_.jpg",
    img5: "https://m.media-amazon.com/images/I/71ZjxJKa16L._UX679_.jpg",
    price: 1449,
    discount: 67,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 107,
    title: `EYEBOGLER Men's Striped Regular Fit T-Shirt (T428HS_Blue XL) EYEBOGLERMenRegularT-Shirt`,
    img: "https://m.media-amazon.com/images/I/51zPkF2QEDL._SY741._SX._UX._SY._UY_.jpg",
    img2: "https://m.media-amazon.com/images/I/51J3B0pv4YL._UX569_.jpg",
    img3: "https://m.media-amazon.com/images/I/51k5XjXCDLL._SY741._SX._UX._SY._UY_.jpg",
    img4: "https://m.media-amazon.com/images/I/51mafXDEOoL._SY741._SX._UX._SY._UY_.jpg",
    img5: "https://m.media-amazon.com/images/I/81+4kqbFVvL._SX679._SX._UX._SY._UY_.jpg",
    price: 1299,
    discount: 69,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 108,
    title: `Urbano Fashion Men's Graphic Printed Round Neck Half Sleeve Slim Fit Cotton T-Shirt`,
    img: "https://m.media-amazon.com/images/I/812LCdKokXL._UX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71CfH9fxKYL._UX679_.jpg",
    img3: "https://m.media-amazon.com/images/I/41T6QdEsZmL._SR38,50_.jpg",
    img4: "https://m.media-amazon.com/images/I/71xLe5pvS5L._UX679_.jpg",
    img5: "https://m.media-amazon.com/images/I/81Qp88He8ZL._UX679_.jpg",
    price: 999,
    discount: 63,
    qty: 1,
    category: "tshirt",
  },
];
const shoes = [
  {
    id: 201,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL._UL1438_.jpg",
    img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img5: "	https://m.media-amazon.com/images/I/51z-s8y0RWL._UL1500_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 202,
    title: `ASIAN Men's Thar-04 Sports Running,Walking & Gym Shoes with Eva Sole Extra Jump Casual Sneaker Shoes for Men's & Boy's…`,
    img: "https://m.media-amazon.com/images/I/610fN3RyKFL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/717P-nWUGkL._UL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/61Gg25qBH6L._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61VgGxQtSwL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61kVGCH4bYL._UL1100_.jpg",
    price: 649,
    discount: 19,
    qty: 1,
    category: "shoes",
  },
  {
    id: 203,
    title: `ASIAN Crystal-13 Sports Running,Walking & Gym Shoes with Crystal Cushion Technology Lightweight Casual Sneaker Shoes for Men's & Boy's`,
    img: "https://m.media-amazon.com/images/I/51rdBvOe1+L._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61-PGOXrVeL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61BNP0y86fL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/51LZUELy+zL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61lep9KLIrL._UL1100_.jpg",
    price: 2299,
    discount: 45,
    qty: 1,
    category: "shoes",
  },
  {
    id: 204,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61utX8kBDlL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/611rLwm1DLL._UL1280_.jpg",
    img3: "https://m.media-amazon.com/images/I/61qgw+hqm5L._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61U70iqOAIL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61yg+IEecXL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 205,
    title: `BRUTON Men's Sports Shoes Sports`,
    img: "https://m.media-amazon.com/images/I/71A7mJgXCxL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71j6TosLiwS._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71iuQCgFToS._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71KXZ0QCypS._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71wg2wFEwjS._UL1500_.jpg",
    price: 1299,
    discount: 70,
    qty: 1,
    category: "shoes",
  },
  {
    id: 206,
    title: `Campus Men's Hurricane Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61+E6-WZBGL._UL1440_.jpg",
    img2: "https://m.media-amazon.com/images/I/61LZrCMUl3L._UL1440_.jpg",
    img3: "https://m.media-amazon.com/images/I/71CALuCptDL._UL1440_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Spy9mHrIL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/61VutC63EhL._UL1440_.jpg",
    price: 1299,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 207,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL._UL1438_.jpg",
    img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/51fOK2ZRVuL.jpg",
    img5: "https://m.media-amazon.com/images/I/51z-s8y0RWL._UL1500_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 208,
    title: `Skechers Mens Glide-Step Sport - New Approa Casual Shoe`,
    img: "https://m.media-amazon.com/images/I/81+AshsrWXL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/51N5bWr2c3L._UL1200_.jpg",
    img3: "https://m.media-amazon.com/images/I/51geeHEMtcL._UL1200_.jpg",
    img4: "https://m.media-amazon.com/images/I/71x+yichhPL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71RpRztxpZL._UL1500_.jpg",
    price: 7449,
    discount: 54,
    qty: 1,
    category: "shoes",
  },
  {
    id: 209,
    title: `Reebok Men's Energy Runner LP Nacho/Conavy/None Running Shoes`,
    img: "https://m.media-amazon.com/images/I/41dXa2CVvPL.jpg",
    img2: "https://m.media-amazon.com/images/I/41dPvRdBOaL.jpg",
    img3: "https://m.media-amazon.com/images/I/61lSwjoTWTL._UL1056_.jpg",
    img4: "https://m.media-amazon.com/images/I/61FxEx82uIL._UL1056_.jpg",
    img5: "https://m.media-amazon.com/images/I/51cCRUVofKL._UL1056_.jpg",
    price: 2499,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
  {
    id: 210,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/616zTSviLpL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61XYz5y6RjL._UL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/611uwBsiJeL._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61fcrs07c6L._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61eY3EBVYCL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 211,
    title: `Adidas Mens Response Solar Running Shoe`,
    img: "https://m.media-amazon.com/images/I/714a6H-+ygL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71EFveuVmUL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71UItRu+HmL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/81YG8m-QY9L._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/51rq9AiMkZL._UL1024_.jpg",
    price: 7599,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 212,
    title: `Adidas Mens Streetgaze M Running Shoes`,
    img: "https://m.media-amazon.com/images/I/71XSP9IVf5L._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81kId-WJOGL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/81vKSHFwhmL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Ln33pOhjL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71XSP9IVf5L._UL1500_.jpg",
    price: 4799,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
];
const tshirtWomen = [
  {
    id: 301,
    title: `FLEXIMAA Women's Cotton Plain V Neck Half Sleeve T-Shirt`,
    img: "https://m.media-amazon.com/images/I/61x8EYIm8hL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61E+qBY6ZmL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/615NTaN+8QL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/51wIOzCS8QL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71Wd3GJZzVL._UL1500_.jpg",
    price: 699,
    discount: 55,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 302,
    title: `TRUEREVO Round Neck Half Sleeve Dry Fit Yoga Workout T Shirt for Women`,
    img: "https://m.media-amazon.com/images/I/71BLosl4pDL._UL1400_.jpg",
    img2: "https://m.media-amazon.com/images/I/71vdvB4u97L._UL1400_.jpg",
    img3: "https://m.media-amazon.com/images/I/71w+zfeypmL._UL1400_.jpg",
    img4: "https://m.media-amazon.com/images/I/71YQoqokl1L._UL1400_.jpg",
    img5: "https://m.media-amazon.com/images/I/61GaR57NOFL._UL1400_.jpg",
    price: 899,
    discount: 17,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 303,
    title: `LEOTUDE Cotton Blend Half Sleeve Oversized T-Shirts for Women's`,
    img: "https://m.media-amazon.com/images/I/61iKv6-unXL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61Fuee5PwiL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61cvw4chTtL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61bzvKukDhL._SX425._SX._UX._SY._UY_.jpg",
    img5: "https://m.media-amazon.com/images/I/61571C4Q3tL._SY550._SX._UX._SY._UY_.jpg",
    price: 1099,
    discount: 73,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 304,
    title: `LEOTUDE Cotton Blend Half Sleeve Oversized Back Printed Women's T-Shirt`,
    img: "https://m.media-amazon.com/images/I/71P5TSBvg9L._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61j4tdciTqL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61z5DyZT31L._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61cvw4chTtL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71P5TSBvg9L._UL1500_.jpg",
    price: 1099,
    discount: 67,
    qty: 1,
    category: "tshirtwomen",
  },
];