const shoes = [
  {
    id: 201,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL._UL1438_.jpg",
    img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img5: "	https://m.media-amazon.com/images/I/51z-s8y0RWL._UL1500_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 202,
    title: `ASIAN Men's Thar-04 Sports Running,Walking & Gym Shoes with Eva Sole Extra Jump Casual Sneaker Shoes for Men's & Boy's…`,
    img: "https://m.media-amazon.com/images/I/610fN3RyKFL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/717P-nWUGkL._UL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/61Gg25qBH6L._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61VgGxQtSwL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61kVGCH4bYL._UL1100_.jpg",
    price: 649,
    discount: 19,
    qty: 1,
    category: "shoes",
  },
  {
    id: 203,
    title: `ASIAN Crystal-13 Sports Running,Walking & Gym Shoes with Crystal Cushion Technology Lightweight Casual Sneaker Shoes for Men's & Boy's`,
    img: "https://m.media-amazon.com/images/I/51rdBvOe1+L._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61-PGOXrVeL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61BNP0y86fL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/51LZUELy+zL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61lep9KLIrL._UL1100_.jpg",
    price: 2299,
    discount: 45,
    qty: 1,
    category: "shoes",
  },
  {
    id: 204,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61utX8kBDlL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/611rLwm1DLL._UL1280_.jpg",
    img3: "https://m.media-amazon.com/images/I/61qgw+hqm5L._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61U70iqOAIL._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61yg+IEecXL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 205,
    title: `BRUTON Men's Sports Shoes Sports`,
    img: "https://m.media-amazon.com/images/I/71A7mJgXCxL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71j6TosLiwS._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71iuQCgFToS._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71KXZ0QCypS._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71wg2wFEwjS._UL1500_.jpg",
    price: 1299,
    discount: 70,
    qty: 1,
    category: "shoes",
  },
  {
    id: 206,
    title: `Campus Men's Hurricane Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61+E6-WZBGL._UL1440_.jpg",
    img2: "https://m.media-amazon.com/images/I/61LZrCMUl3L._UL1440_.jpg",
    img3: "https://m.media-amazon.com/images/I/71CALuCptDL._UL1440_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Spy9mHrIL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/61VutC63EhL._UL1440_.jpg",
    price: 1299,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 207,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    img2: "https://m.media-amazon.com/images/I/61ZOVvtxkHL._UL1438_.jpg",
    img3: "https://m.media-amazon.com/images/I/61K6TxeJUcL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/51fOK2ZRVuL.jpg",
    img5: "https://m.media-amazon.com/images/I/51z-s8y0RWL._UL1500_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 208,
    title: `Skechers Mens Glide-Step Sport - New Approa Casual Shoe`,
    img: "https://m.media-amazon.com/images/I/81+AshsrWXL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/51N5bWr2c3L._UL1200_.jpg",
    img3: "https://m.media-amazon.com/images/I/51geeHEMtcL._UL1200_.jpg",
    img4: "https://m.media-amazon.com/images/I/71x+yichhPL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71RpRztxpZL._UL1500_.jpg",
    price: 7449,
    discount: 54,
    qty: 1,
    category: "shoes",
  },
  {
    id: 209,
    title: `Reebok Men's Energy Runner LP Nacho/Conavy/None Running Shoes`,
    img: "https://m.media-amazon.com/images/I/41dXa2CVvPL.jpg",
    img2: "https://m.media-amazon.com/images/I/41dPvRdBOaL.jpg",
    img3: "https://m.media-amazon.com/images/I/61lSwjoTWTL._UL1056_.jpg",
    img4: "https://m.media-amazon.com/images/I/61FxEx82uIL._UL1056_.jpg",
    img5: "https://m.media-amazon.com/images/I/51cCRUVofKL._UL1056_.jpg",
    price: 2499,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
  {
    id: 210,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/616zTSviLpL._UL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61XYz5y6RjL._UL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/611uwBsiJeL._UL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61fcrs07c6L._UL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/61eY3EBVYCL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 211,
    title: `Adidas Mens Response Solar Running Shoe`,
    img: "https://m.media-amazon.com/images/I/714a6H-+ygL._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71EFveuVmUL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71UItRu+HmL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/81YG8m-QY9L._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/51rq9AiMkZL._UL1024_.jpg",
    price: 7599,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 212,
    title: `Adidas Mens Streetgaze M Running Shoes`,
    img: "https://m.media-amazon.com/images/I/71XSP9IVf5L._UL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81kId-WJOGL._UL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/81vKSHFwhmL._UL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Ln33pOhjL._UL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71XSP9IVf5L._UL1500_.jpg",
    price: 4799,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
];

let dataLoop = shoes.map((x) => {
  return `<div><img src="${x.img}" class="dataImage"/></div>`
})

document.getElementById("dataRender").innerHTML = dataLoop

let img = document.getElementsByClassName("dataImage")
console.log(img);
img[5].style.width = "500px"